### ISSUE TITLE
Query returning empty list of nodes

### ISSUE THREAD

**Issue by akamalov** [ClusterHQ/flocker#2534] opened 2016-01-27 16:06 UTC
Environment: RHEL7
Flocker 1.9.0
Firewall rules: open: any / any

4 storage-node environment. Getting empty array when issuing list:
```
[root@control01 ~]# curl --cacert $PWD/cluster.crt --cert $PWD/user.crt --key $PWD/user.key https://control01.local.net:4523/v1/state/nodes
[]
[root@control01 ~]# 
```
Also noticed that on agent nodes, Flocker Container Agent is failing on some nodes:

###############################################################################
Flocker Container Agent is failing, after a bit...
###############################################################################

```
● flocker-container-agent.service - Flocker Container Agent
   Loaded: loaded (/usr/lib/systemd/system/flocker-container-agent.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Wed 2016-01-27 09:55:56 EST; 44min ago
  Process: 30119 ExecStart=/usr/sbin/flocker-container-agent --journald (code=exited, status=1/FAILURE)
 Main PID: 30119 (code=exited, status=1/FAILURE)

Jan 27 09:55:56 node01.local.net systemd[1]: Unit flocker-container-agent.service entered failed state.
Jan 27 09:55:56 node01.local.net systemd[1]: flocker-container-agent.service failed.
Jan 27 09:55:56 node01.local.net systemd[1]: flocker-container-agent.service holdoff time over, scheduling restart.
Jan 27 09:55:56 node01.local.net systemd[1]: start request repeated too quickly for flocker-container-agent.service
Jan 27 09:55:56 node01.local.net systemd[1]: Failed to start Flocker Container Agent.
Jan 27 09:55:56 node01.local.net systemd[1]: Unit flocker-container-agent.service entered failed state.
Jan 27 09:55:56 node01.local.net systemd[1]: flocker-container-agent.service failed.
```
###############################################################################
From Journal Log
###############################################################################
```
[root@node1 flocker]# journalctl -a -r -u flocker-container-agent
-- Logs begin at Wed 2016-01-27 09:42:41 EST, end at Wed 2016-01-27 10:50:27 EST. --
Jan 27 09:55:56 node1.local.net systemd[1]: flocker-container-agent.service failed.
Jan 27 09:55:56 node1.local.net systemd[1]: Unit flocker-container-agent.service entered failed state.
Jan 27 09:55:56 node1.local.net systemd[1]: Failed to start Flocker Container Agent.
Jan 27 09:55:56 node1.local.net systemd[1]: start request repeated too quickly for flocker-container-agent.service
Jan 27 09:55:56 node1.local.net systemd[1]: flocker-container-agent.service holdoff time over, scheduling restart.
Jan 27 09:55:56 node1.local.net systemd[1]: flocker-container-agent.service failed.
Jan 27 09:55:56 node1.local.net systemd[1]: Unit flocker-container-agent.service entered failed state.
Jan 27 09:55:56 node1.local.net systemd[1]: flocker-container-agent.service: main process exited, code=exited, sta
Jan 27 09:55:56 node1.local.net flocker-container-agent[30119]: TypeError: _get_external_ip() takes exactly 2 argu
Jan 27 09:55:56 node1.local.net flocker-container-agent[30119]: initial = field.initial() if callable(field.initia
Jan 27 09:55:56 node1.local.net flocker-container-agent[30119]: File "/opt/flocker/lib/python2.7/site-packages/pyr
Jan 27 09:55:56 node1.local.net flocker-container-agent[30119]: deployer_factory=deployer_factory
Jan 27 09:55:56 node1.local.net flocker-container-agent[30119]: File "/opt/flocker/lib/python2.7/site-packages/flo
Jan 27 09:55:56 node1.local.net flocker-container-agent[30119]: sys.exit(flocker_container_agent_main())
Jan 27 09:55:56 node1.local.net flocker-container-agent[30119]: File "/usr/sbin/flocker-container-agent", line 11,
Jan 27 09:55:56 node1.local.net flocker-container-agent[30119]: Traceback (most recent call last):
Jan 27 09:55:54 node1.local.net systemd[1]: Starting Flocker Container Agent...
Jan 27 09:55:54 node1.local.net systemd[1]: Started Flocker Container Agent.
Jan 27 09:55:54 node1.local.net systemd[1]: Stopping Flocker Container Agent...
Jan 27 09:55:54 node1.local.net systemd[1]: Starting Flocker Container Agent...
Jan 27 09:55:54 node1.local.net systemd[1]: Started Flocker Container Agent.
Jan 27 09:55:54 node1.local.net systemd[1]: flocker-container-agent.service holdoff time over, scheduling restart.
Jan 27 09:55:53 node1.local.net systemd[1]: flocker-container-agent.service failed.
Jan 27 09:55:53 node1.local.net systemd[1]: Unit flocker-container-agent.service entered failed state.
Jan 27 09:55:53 node1.local.net systemd[1]: flocker-container-agent.service: main process exited, code=exited, sta
Jan 27 09:55:53 node1.local.net flocker-container-agent[30095]: TypeError: _get_external_ip() takes exactly 2 argu
Jan 27 09:55:53 node1.local.net flocker-container-agent[30095]: initial = field.initial() if callable(field.initia
Jan 27 09:55:53 node1.local.net flocker-container-agent[30095]: File "/opt/flocker/lib/python2.7/site-packages/pyr
Jan 27 09:55:53 node1.local.net flocker-container-agent[30095]: deployer_factory=deployer_factory
Jan 27 09:55:53 node1.local.net flocker-container-agent[30095]: File "/opt/flocker/lib/python2.7/site-packages/flo
Jan 27 09:55:53 node1.local.net flocker-container-agent[30095]: sys.exit(flocker_container_agent_main())
Jan 27 09:55:53 node1.local.net flocker-container-agent[30095]: File "/usr/sbin/flocker-container-agent", line 11,
Jan 27 09:55:53 node1.local.net flocker-container-agent[30095]: Traceback (most recent call last):
Jan 27 09:55:51 node1.local.net systemd[1]: Starting Flocker Container Agent...
Jan 27 09:55:51 node1.local.net systemd[1]: Started Flocker Container Agent.
Jan 27 09:55:51 node1.local.net systemd[1]: flocker-container-agent.service holdoff time over, scheduling restart.
Jan 27 09:55:51 node1.local.net systemd[1]: flocker-container-agent.service failed.
Jan 27 09:55:51 node1.local.net systemd[1]: Unit flocker-container-agent.service entered failed state.
Jan 27 09:55:51 node1.local.net systemd[1]: flocker-container-agent.service: main process exited, code=exited, sta
Jan 27 09:55:51 node1.local.net flocker-container-agent[30079]: TypeError: _get_external_ip() takes exactly 2 argu
Jan 27 09:55:51 node1.local.net flocker-container-agent[30079]: initial = field.initial() if callable(field.initia
Jan 27 09:55:51 node1.local.net flocker-container-agent[30079]: File "/opt/flocker/lib/python2.7/site-packages/pyr
Jan 27 09:55:51 node1.local.net flocker-container-agent[30079]: deployer_factory=deployer_factory
Jan 27 09:55:51 node1.local.net flocker-container-agent[30079]: File "/opt/flocker/lib/python2.7/site-packages/flo
Jan 27 09:55:51 node1.local.net flocker-container-agent[30079]: sys.exit(flocker_container_agent_main())
Jan 27 09:55:51 node1.local.net flocker-container-agent[30079]: File "/usr/sbin/flocker-container-agent", line 11,
Jan 27 09:55:51 node1.local.net flocker-container-agent[30079]: Traceback (most recent call last):
Jan 27 09:55:49 node1.local.net systemd[1]: Starting Flocker Container Agent...
Jan 27 09:55:49 node1.local.net systemd[1]: Started Flocker Container Agent.
Jan 27 09:55:49 node1.local.net systemd[1]: flocker-container-agent.service holdoff time over, scheduling restart.
Jan 27 09:55:49 node1.local.net systemd[1]: flocker-container-agent.service failed.
Jan 27 09:55:49 node1.local.net systemd[1]: Unit flocker-container-agent.service entered failed state.
Jan 27 09:55:49 node1.local.net systemd[1]: flocker-container-agent.service: main process exited, code=exited, sta
Jan 27 09:55:48 node1.local.net flocker-container-agent[30063]: TypeError: _get_external_ip() takes exactly 2 argu
Jan 27 09:55:48 node1.local.net flocker-container-agent[30063]: initial = field.initial() if callable(field.initia
Jan 27 09:55:48 node1.local.net flocker-container-agent[30063]: File "/opt/flocker/lib/python2.7/site-packages/pyr
Jan 27 09:55:48 node1.local.net flocker-container-agent[30063]: deployer_factory=deployer_factory
Jan 27 09:55:48 node1.local.net flocker-container-agent[30063]: File "/opt/flocker/lib/python2.7/site-packages/flo
Jan 27 09:55:48 node1.local.net flocker-container-agent[30063]: sys.exit(flocker_container_agent_main())
Jan 27 09:55:48 node1.local.net flocker-container-agent[30063]: File "/usr/sbin/flocker-container-agent", line 11,
Jan 27 09:55:48 node1.local.net flocker-container-agent[30063]: Traceback (most recent call last):
Jan 27 09:55:46 node1.local.net systemd[1]: Starting Flocker Container Agent...
Jan 27 09:55:46 node1.local.net systemd[1]: Started Flocker Container Agent.
Jan 27 09:55:46 node1.local.net systemd[1]: flocker-container-agent.service holdoff time over, scheduling restart.
Jan 27 09:55:46 node1.local.net systemd[1]: flocker-container-agent.service failed.
Jan 27 09:55:46 node1.local.net systemd[1]: Unit flocker-container-agent.service entered failed state.
Jan 27 09:55:46 node1.local.net systemd[1]: flocker-container-agent.service: main process exited, code=exited, sta
Jan 27 09:55:46 node1.local.net flocker-container-agent[30047]: TypeError: _get_external_ip() takes exactly 2 argu
Jan 27 09:55:46 node1.local.net flocker-container-agent[30047]: initial = field.initial() if callable(field.initia
Jan 27 09:55:46 node1.local.net flocker-container-agent[30047]: File "/opt/flocker/lib/python2.7/site-packages/pyr
Jan 27 09:55:46 node1.local.net flocker-container-agent[30047]: deployer_factory=deployer_factory
Jan 27 09:55:46 node1.local.net flocker-container-agent[30047]: File "/opt/flocker/lib/python2.7/site-packages/flo
Jan 27 09:55:46 node1.local.net flocker-container-agent[30047]: sys.exit(flocker_container_agent_main())
Jan 27 09:55:46 node1.local.net flocker-container-agent[30047]: File "/usr/sbin/flocker-container-agent", line 11,
Jan 27 09:55:46 node1.local.net flocker-container-agent[30047]: Traceback (most recent call last):
Jan 27 09:55:44 node1.local.net systemd[1]: Starting Flocker Container Agent...
Jan 27 09:55:44 node1.local.net systemd[1]: Started Flocker Container Agent.
Jan 27 09:55:44 node1.local.net systemd[1]: flocker-container-agent.service holdoff time over, scheduling restart.
Jan 27 09:55:44 node1.local.net systemd[1]: flocker-container-agent.service failed.
Jan 27 09:55:44 node1.local.net systemd[1]: Unit flocker-container-agent.service entered failed state.
Jan 27 09:55:44 node1.local.net systemd[1]: flocker-container-agent.service: main process exited, code=exited, sta
Jan 27 09:55:44 node1.local.net flocker-container-agent[30031]: TypeError: _get_external_ip() takes exactly 2 argu
Jan 27 09:55:44 node1.local.net flocker-container-agent[30031]: initial = field.initial() if callable(field.initia
Jan 27 09:55:44 node1.local.net flocker-container-agent[30031]: File "/opt/flocker/lib/python2.7/site-packages/pyr
Jan 27 09:55:44 node1.local.net flocker-container-agent[30031]: deployer_factory=deployer_factory
Jan 27 09:55:44 node1.local.net flocker-container-agent[30031]: File "/opt/flocker/lib/python2.7/site-packages/flo
Jan 27 09:55:44 node1.local.net flocker-container-agent[30031]: sys.exit(flocker_container_agent_main())
Jan 27 09:55:44 node1.local.net flocker-container-agent[30031]: File "/usr/sbin/flocker-container-agent", line 11,
Jan 27 09:55:44 node1.local.net flocker-container-agent[30031]: Traceback (most recent call last):
Jan 27 09:55:42 node1.local.net systemd[1]: Starting Flocker Container Agent...
Jan 27 09:55:42 node1.local.net systemd[1]: Started Flocker Container Agent.
Jan 27 09:55:42 node1.local.net systemd[1]: flocker-container-agent.service holdoff time over, scheduling restart.
Jan 27 09:55:42 node1.local.net systemd[1]: flocker-container-agent.service failed.
Jan 27 09:55:42 node1.local.net systemd[1]: Unit flocker-container-agent.service entered failed state.
Jan 27 09:55:42 node1.local.net systemd[1]: flocker-container-agent.service: main process exited, code=exited, sta
Jan 27 09:55:42 node1.local.net flocker-container-agent[30015]: TypeError: _get_external_ip() takes exactly 2 argu
Jan 27 09:55:42 node1.local.net flocker-container-agent[30015]: initial = field.initial() if callable(field.initia
Jan 27 09:55:42 node1.local.net flocker-container-agent[30015]: File "/opt/flocker/lib/python2.7/site-packages/pyr
Jan 27 09:55:42 node1.local.net flocker-container-agent[30015]: deployer_factory=deployer_factory
Jan 27 09:55:42 node1.local.net flocker-container-agent[30015]: File "/opt/flocker/lib/python2.7/site-packages/flo
Jan 27 09:55:42 node1.local.net flocker-container-agent[30015]: sys.exit(flocker_container_agent_main())
Jan 27 09:55:42 node1.local.net flocker-container-agent[30015]: File "/usr/sbin/flocker-container-agent", line 11,
Jan 27 09:55:42 node1.local.net flocker-container-agent[30015]: Traceback (most recent call last):
Jan 27 09:55:40 node1.local.net systemd[1]: Starting Flocker Container Agent...
Jan 27 09:55:40 node1.local.net systemd[1]: Started Flocker Container Agent.
Jan 27 09:55:40 node1.local.net systemd[1]: flocker-container-agent.service holdoff time over, scheduling restart.
Jan 27 09:55:40 node1.local.net systemd[1]: flocker-container-agent.service failed.
Jan 27 09:55:40 node1.local.net systemd[1]: Unit flocker-container-agent.service entered failed state.
Jan 27 09:55:40 node1.local.net systemd[1]: flocker-container-agent.service: main process exited, code=exited, sta
Jan 27 09:55:39 node1.local.net flocker-container-agent[29999]: TypeError: _get_external_ip() takes exactly 2 argu
Jan 27 09:55:39 node1.local.net flocker-container-agent[29999]: initial = field.initial() if callable(field.initia
Jan 27 09:55:39 node1.local.net flocker-container-agent[29999]: File "/opt/flocker/lib/python2.7/site-packages/pyr
Jan 27 09:55:39 node1.local.net flocker-container-agent[29999]: deployer_factory=deployer_factory
Jan 27 09:55:39 node1.local.net flocker-container-agent[29999]: File "/opt/flocker/lib/python2.7/site-packages/flo
Jan 27 09:55:39 node1.local.net flocker-container-agent[29999]: sys.exit(flocker_container_agent_main())
Jan 27 09:55:39 node1.local.net flocker-container-agent[29999]: File "/usr/sbin/flocker-container-agent", line 11,
Jan 27 09:55:39 node1.local.net flocker-container-agent[29999]: Traceback (most recent call last):
Jan 27 09:55:37 node1.local.net systemd[1]: Starting Flocker Container Agent...
Jan 27 09:55:37 node1.local.net systemd[1]: Started Flocker Container Agent.
Jan 27 09:55:37 node1.local.net systemd[1]: flocker-container-agent.service holdoff time over, scheduling restart.
Jan 27 09:55:37 node1.local.net systemd[1]: flocker-container-agent.service failed.
Jan 27 09:55:37 node1.local.net systemd[1]: Unit flocker-container-agent.service entered failed state.
Jan 27 09:55:37 node1.local.net systemd[1]: flocker-container-agent.service: main process exited, code=exited, sta
Jan 27 09:55:37 node1.local.net flocker-container-agent[29982]: TypeError: _get_external_ip() takes exactly 2 argu
Jan 27 09:55:37 node1.local.net flocker-container-agent[29982]: initial = field.initial() if callable(field.initia
Jan 27 09:55:37 node1.local.net flocker-container-agent[29982]: File "/opt/flocker/lib/python2.7/site-packages/pyr
Jan 27 09:55:37 node1.local.net flocker-container-agent[29982]: deployer_factory=deployer_factory
Jan 27 09:55:37 node1.local.net flocker-container-agent[29982]: File "/opt/flocker/lib/python2.7/site-packages/flo
Jan 27 09:55:37 node1.local.net flocker-container-agent[29982]: sys.exit(flocker_container_agent_main())
Jan 27 09:55:37 node1.local.net flocker-container-agent[29982]: File "/usr/sbin/flocker-container-agent", line 11,
Jan 27 09:55:37 node1.local.net flocker-container-agent[29982]: Traceback (most recent call last):
Jan 27 09:55:35 node1.local.net systemd[1]: Starting Flocker Container Agent...
Jan 27 09:55:35 node1.local.net systemd[1]: Started Flocker Container Agent.
Jan 27 09:55:35 node1.local.net systemd[1]: flocker-container-agent.service holdoff time over, scheduling restart.
lines 91-135
...
```

Any help what could be causing it ?

Thanks,

Alex

**Comment by wallnerryan** [comment] 2016-01-27 17:18
Hi @akamalov, i responded to you on google groups. https://groups.google.com/forum/#!topic/flocker-users/OrAxBIcuxCM

(this is a duplicate of the google groups question)

**Comment by akamalov** [comment] 2016-01-27 18:05
Sent tar files, Ryan. Thanks again!!

**Comment by wallnerryan** [comment] 2016-02-01 16:16
closing as the issues were container agent, even though more issues exist for RHEL 7 it seems. We can open more issues specific to these issues if needed.

**Closed by wallnerryan** 2016-02-01 16:16 UTC
