### ISSUE TITLE
Flocker not working with OpenStack Cinder on CoreOS

### ISSUE THREAD

**Issue by sindrepm** [ClusterHQ/flocker#2712] opened 2016-03-21 14:49 UTC
I am running Flocker in containers on CoreOS instances provisioned through OpenStack, as per the instructions here: https://docs.clusterhq.com/en/latest/supported/flockercontainers.html#flocker-containers.

The containers start up fine, but the dataset agent logs the following error:

`{"exception": "flocker.node.agents.blockdevice.UnknownInstanceID", "task_level": [2, 2, 5], "action_type": "flocker:agent:discovery", "reason": "Could not find valid instance ID for <flocker.node.agents.cinder.CinderBlockDeviceAPI object at 0x7fe53ab23650>", "timestamp": 1458571401.036858, "task_uuid": "5c5cf3d1-7249-4f88-ac89-7b989af89f2b", "action_status": "failed"}`

Flocker version: 1.10.2
CoreOS version: 899.11.0
OpenStack version: kilo

**Comment by wallnerryan** [comment] 2016-03-21 14:58
Thanks @sindrepm Will look into this for you. Thanks for reporting.

related: https://clusterhq.atlassian.net/browse/FLOC-2281

**Comment by sindrepm** [comment] 2016-03-21 15:47
Hi @wallnerryan 

I had a look at FLOC-2281 and also digged a bit into the code of the cinder plugin. From the logs it seems to me that `api_ips` contains the IP (private and public) of multiple nodes in my cluster, while it should only contain the IPs of the given node if I understand the code correctly. Thus, the [code on line #442](https://github.com/ClusterHQ/flocker/blob/master/flocker/node/agents/cinder.py#L442) fails because the list of API IPs are not a subset of the local IPs to the node.

So for some reason, the following call seems to return IPs from multiple nodes:

`api_addresses = _extract_nova_server_addresses(server.addresses)`

I might be totally wrong here, but at least that is what I could read from it. For debugging purposes, would it be an idea to isolate the method `compute_instance_id` and run it from within the dataset agent container to see what the Nova API actually returns?

**Comment by wallnerryan** [comment] 2016-03-21 15:49
@sindrepm So i deployed CoreOS 899.11.0 and Flocker 1.10.2 with Cinder 13.0.0 and was not able to reproduce your problem yet.

**Comment by sindrepm** [comment] 2016-03-21 20:51
@wallnerryan I think you are right, the issue is related to the IPs. As @wallrj commented [here](https://clusterhq.atlassian.net/browse/FLOC-2281), the list of IPs returned from Nova contains a IPv6 IP (2607:ff68:100:36::2ee) which is not present on the host. This causes the check to fail and throws the "no matching instance ID" error.

I need to look into why the IPv6 address is not present on the host. It is not listed at all in the output of `ip addr`.

You said: 

> Its okay that api_addresses has multiple, as long as your local addresses are a subset.

I think the code actually does the opposite. api_addresses must be a subset of local_ips. Anyway,  maybe the subset check is not the best way to deal with this. It could be situations (like this) where the api_addresses contains IPs that are not mapped on the host, and the local IPs would definitely contain addresses that are not part of the API addresses (e.g. docker IPs).

Would it be better to instead check if **at least** one IP is found in both sets? I think that should suffice to identify the instance and the logic would be less prone to edge cases like this?

**Comment by wallrj** [comment] 2016-03-21 23:38
Thanks @sindrepm I updated https://clusterhq.atlassian.net/browse/FLOC-2966 with a summary of our discussion.
Also note that this is essentially the same problem as #2693 so I'll close this for now.

I would like to know why the IPv6 address didn't appear on your CoreOS host. Perhaps it was a floating IP address routing traffic to the node using network address translation. I.e. not directly assigned to the host.

**Closed by wallrj** 2016-03-21 23:38 UTC
Labels: kind: installing-flocker, kind: openstack, kind: using flocker
