### ISSUE TITLE
If Nova instance has floating IP attached then cinder driver does not works

### ISSUE THREAD

**Issue by PradeepSingh1988** [ClusterHQ/flocker#2693] opened 2016-03-14 11:30 UTC
In file `/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/cinder.py` in function `compute_instance_id` , if nova instance has floating IP attached to it  then it does not works.
Below cal is failing:
`if api_addresses and api_addresses.issubset(local_ips):`.

I have below content in api_addresses and local_ips variable:
`api_addresses: set([IPv4Address('10.0.16.4'), IPv4Address('192.168.0.108')])
local_ips: set([IPv6Address('fe80::42:98ff:feec:ed21'), IPv6Address('fe80::f816:3eff:fe36:bbac'), IPv4Address('10.0.16.4'), IPv4Address('127.0.0.1'), IPv6Address('::1'), IPv4Address('10.200.9.0'), IPv4Address('10.200.9.1')])`

As we can see floatingIP 192.168.0.108 is not there in local_ips.
I dont know why its not there but i think above call should be modifies as :
`if api_addresses and len(api_addresses.intersection(local_ips)) > 0:`

**Comment by wallnerryan** [comment] 2016-03-14 13:11
Thanks @PradeepSingh1988 we will look into this, thanks for reporting.

**Comment by wallnerryan** [comment] 2016-03-14 13:17
@PradeepSingh1988  I also see that this looks like it was addresses, or was similarly addresses in https://github.com/ClusterHQ/flocker/issues/1903.

**Comment by wallnerryan** [comment] 2016-03-14 13:23
@PradeepSingh1988 just seeing that we have a proposed fix that wasn't merged. I will update this issue when it does.

Thanks

**Comment by wallnerryan** [comment] 2016-03-21 13:43
related to https://github.com/ClusterHQ/flocker/issues/1903

**Comment by wallrj** [comment] 2016-03-21 23:46
Thanks @PradeepSingh1988 another user reported a similar problem today in #2712.

We'll track this in https://clusterhq.atlassian.net/browse/FLOC-2966 and I'll try and get it prioritized for the next release.
Closing as a duplicate of #1903

**Closed by wallrj** 2016-03-21 23:46 UTC
Labels: kind: openstack, kind: using flocker
