### ISSUE TITLE
docker volume rm  <volume_name>  command does not work ?

### ISSUE THREAD

**Issue by akhilcalsoft** [ClusterHQ/flocker#2863] opened 2016-07-14 10:51 UTC
Hi Team,

docker volume rm  <volume_name>  command does not work for flocker volume ?

Please confirm above issue is valid or not.

**Comment by wallnerryan** [comment] 2016-07-27 18:39
duplicate of https://github.com/ClusterHQ/flocker/issues/2764

**Closed by wallnerryan** 2016-07-27 18:39 UTC
