### ISSUE TITLE
Flocker Openstack cinder backend

### ISSUE THREAD

**Issue by kumarsarath588** [ClusterHQ/flocker#2759] opened 2016-04-13 13:07 UTC
Hey,

I have 3 nodes docker setup Swarm Master(flocker-control) + Swarm Node1 +Swarm Node 2. (Openstack cinder backend)

Creating a volume "docker volume create -d flocker vol1" is sucessful.

But assigning the volume "vol1" to a container  is failing.

Console : docker run -it --net network1 -v test_vol1:/data --rm --name box2 busybox
docker: Error response from daemon: 500 Internal Server Error: ConnectingCancelledError: IPv4Address(TCP, '192.168.202.111', 4523).

Swarm Node Flocker Logs: 

{"exception": "flocker.node.agents.blockdevice.UnknownInstanceID", "task_level": [2, 2, 5], "action_type": "flocker:agent:discovery", "reason": "Could not find valid instance ID for <flocker.node.agents.cinder.CinderBlockDeviceAPI object at 0x7f0503b02cd0>", "timestamp": 1460551863.717013, "task_uuid": "e2678d3a-fa29-4003-92b3-1654e67405c2", "action_status": "failed"}

Backend Config:
"control-service:
    hostname: "192.168.202.111"
    port: 4524
dataset:
    backend: "openstack"
    verify_peer: False
    region: "RegionOne"
    auth_plugin: "password"
    username: "admin"
    tenant_name: "admin"
    password: "XXXXXXXXXXXXX"
    auth_url: "http://192.168.201.11:5000/v2.0"
version: 1"

**Comment by wallnerryan** [comment] 2016-04-13 14:23
Hi,

There are certain cases where we do not detect the openstack instance properly.

This is a duplicate of some others, will close this in favor of #1903 

See: https://github.com/ClusterHQ/flocker/issues/1903
See: https://github.com/ClusterHQ/flocker/issues/2712
See: https://github.com/ClusterHQ/flocker/issues/2693

We are currently working on this for a fix See: https://clusterhq.atlassian.net/browse/FLOC-2966 for up to date

**Closed by wallnerryan** 2016-04-13 14:23 UTC
