### ISSUE TITLE
dockerfile/redis no longer exists

### ISSUE THREAD

**Issue by lukemarsden** [ClusterHQ/flocker#1356] opened 2015-04-30 10:01 UTC
this means the getting started guide is broken, i think :(

**Comment by lukemarsden** [comment] 2015-04-30 10:03
I think it's just called "redis" now

**Comment by msh100** [comment] 2015-04-30 10:03
https://blog.docker.com/2015/03/updates-available-to-popular-repos-update-your-images/

This is the cause

**Comment by adamtheturtle** [comment] 2015-04-30 10:10
Thank you both. I have made an issue to change this (and the general case) in our internal issue tracker at https://clusterhq.atlassian.net/browse/FLOC-1789. You can follow progress of this issue there. I am closing this issue but feel free to re-open it and comment.

**Closed by adamtheturtle** 2015-04-30 10:10 UTC

**Comment by lukemarsden** [comment] 2015-04-30 10:22
Thanks Adam. Ftr I think the vagrant demo may still work because it will have this image cached in the vagrant box. Could @binocarlos please check this?

**Comment by binocarlos** [comment] 2015-04-30 11:14
Can confirm what @lukemarsden says - the image `dockerfile/redis` is cached in the Vagrant box:

```bash
[vagrant@node1 ~]$ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
dockerfile/redis    latest              1d2875ab73c9        5 weeks ago         418.9 MB
clusterhq/flask     latest              fb9b1201592f        3 months ago        896.7 MB
busybox             latest              4986bf8c1536        3 months ago        2.43 MB
clusterhq/mongodb   latest              1fe01bb7e1da        8 months ago        51.32 MB
```

 but not on the Dockerhub:

```bash
[vagrant@node1 ~]$ sudo docker rmi dockerfile/redis
Untagged: dockerfile/redis:latest
Deleted: 1d2875ab73c906da5d4cb215721fef20ec9fc1658cc3235866d861a5c4e870a1
Deleted: 51bab73a70d12fef003c8d418d5726abb28ccf6a5855acc1f78922527b532aec
Deleted: 0b7bf3896a9a0a338a373eb0bd955070e47a6968333a9a426fbd26a298d07a7c
Deleted: d3b6803665c844ed6fca03069734dadec96d3153e24ad1df3165425ab6e736e7
Deleted: 0611aa988173a5a9fe9c2694e9b93e2491d7bd008f7bd436279bd9fce7ea0aa2
Deleted: b87155bee962c0971aad177e7d4b98bfe9d13058108e80f202c93853234c2385
Deleted: d68e2305f8edda4f52145dbe410be170597549f08533905092c3f21a2e1df869
Deleted: 709d157e17384e59683d3adc0e26a9ab8bd123a880883126b9cbd7afc876ff3f
Deleted: d8a81e277706f76eed580485972dd3e17a8442fee73efc4b740434ec891b158b
Deleted: c510b5fa9855f0335f487c178227f24f96a5ad37caa819c8acbc46c01154e18b
Deleted: 6c2617291f446bcf29794a4567f659e487cf2fd4f6296ca2aafd032956be7b11
Deleted: 23349001223baeba11ce61bfd019fd2730a79841986dcbfc11e859afc22fc0e0
Deleted: d0955f21bf24f5bfffd32d2d0bb669d0564701c271bc3dfc64cfc5adfdec2d07
Deleted: 9fec74352904baf5ab5237caa39a84b0af5c593dc7cc08839e2ba65193024507
Deleted: a1a958a248181c9aa6413848cd67646e5afb9797f1a3da5995c7a636f050f537
Deleted: f3c84ac3a0533f691c9fea4cc2ceaaf43baec22bf8d6a479e069f6d814be9b86
[vagrant@node1 ~]$ sudo docker pull dockerfile/redis
Pulling repository dockerfile/redis
FATA[0005] Error: image dockerfile/redis:latest not found
```

**Comment by lukemarsden** [comment] 2015-04-30 13:30
Thanks @binocarlos just to confirm did you also run through the demo and found that it works?

**Comment by binocarlos** [comment] 2015-04-30 13:34
@lukemarsden yes - I had a small issue to begin with so deleted my vagrant boxes (to simulate a fresh run-through) - the getting started guide worked perfectly once I did this - summary: it works :)

**Comment by lukemarsden** [comment] 2015-04-30 13:39
Thanks @binocarlos !

**Comment by shay-berman** [comment] 2016-05-16 16:03
I encounter the same issue, the tuturial didn't work because dockerfile/redis is not exist.
Please the doc so it will use redis instead of dockerfile/redis.
https://github.com/binocarlos/trueability/blob/master/tutorials/moving_a_data_volume.md

Thanks

**Comment by wallnerryan** [comment] 2016-05-17 15:37
@shay-berman FYI this is an old tutorial and `flocker-deploy` has also been deprecated. Try of the newer demos from our docs.

**Comment by shay-berman** [comment] 2016-05-17 20:12
Hi Ryan,

Could you please send me link to the updated demo \ tutorial ?
how do I suppose to know that flocker-deploy is deprecated if it comes with
the latest flocker version(and also mentioned in many videos and
tutorials)?
(Suggestion - maybe you should mentioned the deprication in the help of the
command or even as output of the command)

Can you refer me to the command that replace the flocker-deploy?

Thanks a lot

**Comment by shay-berman** [comment] 2016-05-18 05:23
Hi Ryan

I saw that there is new command called flockerctl but it says its an
experimental project ->
https://docs.clusterhq.com/en/latest/flocker-features/flockerctl.html

is this the command that replace the flocker-deploy?

**Comment by shay-berman** [comment] 2016-05-18 13:31
I saw in the clusterHQ web site that you asking to run : curl -sSL
https://get.flocker.io/ | sh     in order to get more flocker commands.

I installed the flocker by using this page ->
https://docs.clusterhq.com/en/latest/flocker-standalone/manual-install.html
on the client i just got the following commands : flocker flocker-ca
flocker-deploy

and on the flocker node i got these commands : flocker-benchmark
flocker-container-agent flocker-dataset-agent flocker-diagnostics
flocker-node-era  flocker-ca flocker-control flocker-deploy
flocker-docker-plugin flocker-volume

Should I need to run this  curl -sSL https://get.flocker.io/ | sh    to get
more relevant commands?

**Comment by wallnerryan** [comment] 2016-05-18 13:57
@shay-berman the package `clusterhq-flocker-cli` gives you ` flocker flocker-ca
flocker-deploy` 

the package `clusterhq-flocker-node` gives you `flocker-benchmark
flocker-container-agent flocker-dataset-agent flocker-diagnostics
flocker-node-era  flocker-ca flocker-control flocker-deploy
flocker-docker-plugin flocker-volume`

you need `clusterhq-flocker-node` on all agent and control nodes.
