### ISSUE TITLE
Destroy dataset, but volume data and dir is exist on nodes?

### ISSUE THREAD

**Issue by ttllyy** [ClusterHQ/flocker#2235] opened 2015-11-26 09:43 UTC
flocker version: 1.7.1
backend:zfs
node1 uuid: cat /etc/flocker/volume.json
{"version": 1, "uuid": "b083f1ba-75b0-41dd-8b2a-33bd4e624e81"}
node2 uuid: cat /etc/flocker/volume.json
{"version": 1, "uuid": "1172eee5-35e1-406c-9ad4-863609b51291"}

I create dataset on node1:
DATASET SIZE METADATA STATUS SERVER
3cac6429-0d25-4eda-a595-3e93898a2150 5.00G name=my-vol-demo3 attached ✅ eb4f2b7d (node1)

I run same pod on node1 and node2. So there are related /flocker/xxx dir on node1 and node2.
I destroy dataset my-vol-demo3.
But related /flocker/xxx dir isn't removed and some data isn't removed.
I cann't manual remove related dir. Why?

I create dataset my-vol-demo3(same name) on node1 again.
Create new /flocker/xxxx dir on node1.
But I create same pod on node1 fail.
Unable to mount volumes for pod "flocker-web-x1_default": The volume 'my-vol-demo3' is not available in Flocker. You need to create this manually with Flocker CLI before using it.

**Comment by wallnerryan** [comment] 2015-12-04 16:02
dupe of https://github.com/ClusterHQ/flocker/issues/2234 I will address this in the first issue created

**Closed by wallnerryan** 2015-12-04 16:02 UTC
